# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "pugixml"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    open-pull-requests-limit: 1 
    labels:
      - "Comp:Core"
      - "Priority:1-Critical" 
