[project]
name = "1D-MCSolver"
version = "0.1.0"
description = "Add a short description here"
authors = ["Nathan Glaser <nglaser3@illinois.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
compile = "g++ -std=c++11 -o mc.exe main.cpp"

[dependencies]
pugixml = ">=1.14,<2"
